import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 两个侧栏都按目录自动生成：
 *  docs      → 精选治理原文（快速开始 / 架构与治理 / 运行契约 / 变更与历史）
 *  reference → 三仓注册表与平台读数自动生成的参考目录
 * 顺序由 sync-docs 写入的 sidebar_position 与目录 _category_.json 决定，不在这里手抄条目。
 */
const sidebars: SidebarsConfig = {
  docs: { type: 'autogenerated', dirName: '.' },
  reference: { type: 'autogenerated', dirName: '.' },
};

export default sidebars;
